services:
  # A Docker web service
  - type: web
    name: student-course-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: student-course-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9

databases:
  - name: student-course-db
    databaseName: student_course_db
    user: student_course_user
    plan: free
